name: My First Workflow
on:
  push: 
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref_name}}